csesoc/website

Backend/Makefile
Makefile
Readme.md
docker-compose.yml
postgres/Dockerfile
postgres/infile

Postgres w21 88

---

postgres/infile

- added schema
- added constraints to ensure logical tree structure
- added function so no one else has to experience the pain i felt

Implemented schema

---

Backend/filesystem/endpoints.go
Backend/filesystem/service.go
Backend/filesystem/service_test.go
postgres/infile

In the future I will need to refactor the filesytem/endpoints file to abstract a lot of error checking

Changes to Schema + Filesystem Entity Deletion

---

Backend/filesystem/endpoints.go
Backend/httpUtil/main.go

Package serves as a way to easilly handle http requests/responses

Added HTTPUtil package

---

Cms_frontend/.eslintrc.yml
Cms_frontend/package.json
Cms_frontend/src/components/NewDialogue/TemplateChip.tsx
Cms_frontend/src/components/NewDialogue/TemplateSelector.tsx
Cms_frontend/src/components/SideBar/SideBar.tsx
Cms_frontend/src/pages/Dashboard.tsx

Self explanatory.
I left the rules fairly lax and removed some more annoying things like CRLF/LF on linebreaks, quote rules and semicolons.

Added ESlint and fixed any linting issues present

---

Backend/database/contexts/live_context.go
Backend/database/contexts/main.go
Backend/database/contexts/testing_context.go
Backend/database/repositories/filesystem.go
Backend/database/repositories/tests/filesystem_test.go
Postgres/create_tables.sql

Removing Children HStore from Schema

---

.github/workflows/ci.yml
Frontend/package.json
Frontend/src/App.tsx
Frontend/src/cse-ui-kit/buttons/Button.stories.tsx
Frontend/src/cse-ui-kit/buttons/index.ts
Frontend/src/packages/dashboard/components/ConfirmationModal/ConfirmationWindow.tsx
Frontend/tsconfig.json

- Frontend needed a way to visually render and test resuable components completely isolated from the integreation of the component with the rest of the app, that is why we are using storybook
- Frontend also required a way to prevent introducing breaking changes to main branch, and running a pre-push type check and eslint check will help prevent small things from breaking main
- Added storybook and created a template for it
- Added more pre push CI/CD steps for FE

[CMS-226] Adding more storybook templates, Adding more CI/CD checks for frontend

---

Backend/endpoints/tests/filesystem_test.go

Added tests for createnewentity and deletefilesystementity endpoints

added createnewentity and deleteentity http endpoint tests

---

.github/dependabot.yml

This PR adds dependabot to this repository.

feat(ci): setup dependabot

---

CODEOWNERS
Frontend/package.json
Frontend/src/App.tsx

- Updated react-router dom to use v6 syntax

update to react router dom to v6

---

Next/src/pages/Homepage.tsx

Preview of the homepage wit scroll down icon implemented:

[CMS-243] implemented scroll down icon

---

Frontend/src/cse-ui-kit/CreateMediaBlock_button/CreateMediaBlock-Styled.tsx
Frontend/src/cse-ui-kit/CreateMediaBlock_button/CreateMediaBlock.stories.tsx
Frontend/src/cse-ui-kit/CreateMediaBlock_button/CreateMediaBlock.tsx
Frontend/src/cse-ui-kit/CreateMediaBlock_button/index.ts

- Button to create media content block for content upload
- Created button UI similar to the content and heading block buttons

[CMS-280] Create Create Media Block button

---

backend/OTClient/operation.ts

This PR just adds the transform functions to the OT client

Added OT Client transform functions

---

backend/editor/OT/data/applicator.go
backend/editor/OT/data/operations.go
backend/editor/OT/data/tests/models_test.go
backend/editor/OT/data/traversal.go

- Added indice pathing to traversal and getter function, as well as helper stubs (to be implemented post AST)
- Corrected the corresponding tests with placeholders for to be done TLB code

Indice Pathing

---

frontend/package-lock.json
frontend/src/deprecated/components/Editor/EditorHeader.tsx
frontend/src/deprecated/components/FileRenderer_OLD/FileContainer.tsx
frontend/src/packages/dashboard/components/Directory.tsx
frontend/src/packages/dashboard/components/FileRenderer/FileContainer.tsx
frontend/src/packages/dashboard/components/FileRenderer/FolderContainer.tsx
frontend/src/packages/dashboard/components/FileRenderer/Renamable.tsx
frontend/src/packages/dashboard/components/SideBar/SideBar.tsx

- Changed dashboard button styling
- Fixed document naming input style
- Removed header text for editor

[CMS-299] Modify dashboard button style and editor header

---

next/package-lock.json
next/package.json
next/src/pages/MiniEvents.tsx
next/src/pages/MiniHomepage.tsx
next/src/pages/MiniResources.tsx
next/src/pages/MiniSupport.tsx
next/src/pages/index.tsx
next/src/styles/globalStyles.ts
next/src/styles/motion.tsx
next/src/svgs/HPCurve.svg
next/src/svgs/HPCurve.tsx

adding framer motion animations to homepage

Nextjs UI improvements

---

next/src/pages/MiniEvents.tsx
next/src/pages/MiniHomepage.tsx
next/src/pages/MiniSupport.tsx
next/src/pages/index.tsx
next/src/styles/motion.tsx

feat(next): landing page various spacing improvements and ui fixes

---

backend/endpoints/volume_endpoints.go
frontend/src/cse-ui-kit/PublishDocument_button/PublishDocument-Styled.tsx
frontend/src/cse-ui-kit/PublishDocument_button/PublishDocument.tsx
frontend/src/cse-ui-kit/PublishDocument_button/index.ts
frontend/src/cse-ui-kit/SyncDocument_button/SyncDocument-Styled.tsx
frontend/src/cse-ui-kit/SyncDocument_button/SyncDocument.tsx
frontend/src/cse-ui-kit/SyncDocument_button/index.ts
frontend/src/packages/dashboard/components/ConfirmationModal/ConfirmationWindow.tsx
frontend/src/packages/editor/index.tsx
next/src/components/blog/Blog.tsx
next/src/components/blog/types.ts
next/src/pages/blog/[bid].tsx
next/src/pages/blog/index.tsx

- Implemented dynamic route name for Next.js blogs
- Enabled proper server-side rendering for Next.js blogs
- Improved filesystem confirmation window UI
- Improved editor button UI

[CMS-302] Editor and Next.js improvements

---

next/src/components/aboutus/AboutUs-Styled.tsx
next/src/components/aboutus/Sphere-Styled.tsx
next/src/pages/MiniAboutUs.tsx

feat(frontend): add more info sphere link

---

CODEOWNERS

Updating codeowners file to include new leads

chore(cms): Updating codeowners file

---

backend/database/repositories/tests/dockerfilesystem_test.go
backend/endpoints/tests/handler_test.go

test signature

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/redux-state/configure-store.ts
frontend/src/redux-state/index.ts

Currently, the redux state when navigating the file system is not persisting on the reload of a page. We want each instance/tab to have its own state persist on reload.
- npm installed redux-persist
- wrapped App.tsx routes with PersistGate
- implemented persistor in configure-store.ts

[WEB-33] Make directory persist during reloads
