Backend/filesystem/endpoints.go
Backend/filesystem/service.go
Backend/filesystem/service_test.go
Backend/main.go

This PR implements a function which pulls all entity children as a list of IDs. This function uses the children row in the db, so it is safe to remove the parent row in the future without changes to this property. Unit tests are included and there is little else to report for this :)

W21 75 filesystemchildren

---

Frontend/src/packages/dashboard/api/index.ts

- after creating a new page and trying to rename the page for the first time, the rename doesn't work (after entering the rename, it goes back to the initial name)
- this was because the page didn't have a valid ID intially.
- Changed api for newFile to return the ID instead of JSON

[EASY][BUG] Filename rename doesnt actually change the name

---

Backend/endpoints/auth_endpoints.go
Backend/endpoints/filesystem_endpoints.go
Backend/endpoints/main.go
Backend/endpoints/util.go

- Make the function `ParseParamsToSchema` return the http status code instead of a bool
- ~~Make `Handler` functions return the error~~
- ~~Adjust HTTP message to be the error if one was raised~~
Last two points are ignored since the server will only return a response if there was no error

[CMS-254] Backend - Improve error handling

---

Backend/Dockerfile.development
Config/.env.dev.example
Frontend/Dockerfile.development
Makefile
Next/Dockerfile.development
docker-compose.yml

Dockerfiles were changed to production dockerfiles, breaking development docker-compose
- added dockerfile.development
- updated docker-compose to use development dockerfiles
- updated makefile to allow for `cms-only` and `next-only` builds

[CMS-283] Fixing broken development dockerfiles

---

Backend/database/contexts/live_context.go
Backend/database/contexts/main.go
Backend/environment/config.go

This PR allows the postgres address to be set via the `POSTGRES_HOST` environment variable.

feat(backend): move postgres host to env var

---

Frontend/src/cse-ui-kit/contentblock/contentblock-Styled.tsx
Frontend/src/packages/editor/components/EditorBlock.tsx

- To fill the screen and make text entry more ergonomic with longer lines
- Changed width of block
- Ensured style buttons (bold, underline, etc) stayed in the same relative position to the top left of the resized block
Note editor is currently unable to be previewed and so UI screenshot may not be very meaningful

[CMS-273] Resize ContentBlockWrapper

---

Backend/endpoints/filesystem_endpoints.go
Backend/endpoints/registration.go
Backend/endpoints/tests/filesystem_test.go
Backend/endpoints/util.go

A PR to handle the uploading of images, though have some questions:
- Should we make a new private function to creation and adding of entities to the fs, so that `CreateNewEntity` and `UploadImage` can call it, reducing additional code
- Should we also add logging to `ParseParamsToSchema`?

[CMS-236] Add image upload endpoint

---

Backend/editor/models/tests/models_test.go
Backend/editor/models/traversal.go

- Change to use `strconv.Atoi` instead of `strconv.ParseInt`
- Add bonus test cases for invalid case
- Return error if the ascii to integer fails (if there was an error, index would be 0) resulting in invalid field)
Also wondering if there is a way to do deep equality checks - this would make the traversal testing less rigid, i.e. we check that the struct returned from traversal has deep equality with struct in `setupDocument`

Fix edge case in traversal and add more test cases for invalid inputs

---

backend/editor/OT/client_view.go
backend/editor/OT/data/operationModel.go
backend/editor/OT/document_server.go
backend/editor/OT/worker.go

PR just adds a record of all operations the server has ever applied, this is used to correctly transform incoming client operations against the requested base server OP as described in: https://lively-kernel.org/repository/webwerkstatt/projects/Collaboration/paper/Jupiter.pdf 
In the future to reduce memory usage we should dynamically remove OPs from this set that could no longer reasonably be the base for any incoming client operation (this could perhaps be achieve by associating a count with each index and decrementing until we hit 0?) but that's something to think about later.

OT Server - Adding Operation History Record

---

backend/database/repositories/dockerfilesystem.go
backend/database/repositories/filesystem.go
backend/database/repositories/main.go
backend/database/repositories/repository_interfaces.go
backend/database/repositories/tests/filesystem_test.go
backend/editor/diffSync/document/manager.go
backend/editor/pessimistic/main.go
backend/endpoints/auth_endpoints.go
backend/endpoints/dependency_factory.go
backend/endpoints/editor_endpoints.go
backend/endpoints/filesystem_endpoints.go
backend/endpoints/main.go
backend/endpoints/mocks/dependency_factory_mock.go
backend/endpoints/models/filesystem_models.go
backend/endpoints/models/user_models.go
backend/endpoints/tests/filesystem_test.go
backend/endpoints/volume_endpoints.go

This PR just simplifies the dependency factory + the repository constructors, neither of them now rely on magic constants for initiating repos/dependencies allowing for easier interface mocking and better type safety

Dependency Factory Refactor - Simplifying interface + Removing reflection

---

backend/endpoints/models/volume_models.go
backend/endpoints/volume_endpoints.go

Modifying upload document to only support uploading a document once, prevents issues with ppl overriding data

feat(cms): Upload Document - Only support single uploads

---

frontend/package-lock.json
frontend/package.json
frontend/src/packages/editor/api/OTClient/README.md
frontend/src/packages/editor/api/OTClient/client.ts
frontend/src/packages/editor/api/OTClient/operation.ts
frontend/src/packages/editor/api/OTClient/operationQueue.ts
frontend/src/packages/editor/api/OTClient/util.ts
frontend/src/packages/editor/api/cmsFS/volumes.ts
frontend/src/packages/editor/componentFactory.tsx
frontend/src/packages/editor/components/EditorBlock.tsx
frontend/src/packages/editor/components/HeadingBlock.tsx
frontend/src/packages/editor/index.tsx
frontend/src/packages/editor/operationManager.tsx
frontend/src/packages/editor/types.ts
frontend/tsconfig.json
postgres/Dockerfile

PR adds the first stage of the required changes to the front-end in order to support operational transform. This PR captures SlateJS operations and propagates them to a central place for delivery to the server. The PR after this will focus on translating SlateJS operations into the CMS operation format + sending them to the server and the final PR will focus on applying operations sent from the server to the editor.

OT Frontend Changes - Stage 1

---

backend/endpoints/models/user_models.go
backend/endpoints/tests/auth_test.go

Hello!
This adds tests for `TestLogin` and `TestLogout` in [`auth_endpoints.go`](https://github.com/csesoc/website/blob/CMS-306/backend/endpoints/auth_endpoints.go). Sorry for taking so long.
They test only the current behaviour on the typical success case, that is, logging in as a user that exists and logging out a user that has logged in. There is definitely space to add tests for error cases.
Part of the success behaviour is that `TestLogin` returns the status code [`301 Moved Permanently`](https://http.cat/301), which seems dubious to me. That seems more appropriate for deprecated routes, especially since RFC 2616 says that it indicates the client should update references to point to the redirect and that the response is cacheable.
Lastly, I exported `(u *User) HashPassword` …

[CMS-306] Thomas L - Onboarding

---

README.md

running the current command returns the following output:
```
docker: 'volumes' is not a docker command.
See 'docker --help'
```
because `volumes` is not a docker command, but `volume` is, so this PR fixes this docker command by changing `docker volumes` to `docker volume` so that it uses the correct docker command that doesn't return an error, as `docker volume` is valid

docs: correct docker command from `volumes` to `volume`

---

frontend/src/packages/dashboard/components/FileRenderer/FileContainer.tsx

Currently, in order to edit a document, the user has to select the file and then select the edit button. Double clicking let's user more fluidly access their document.
- Implemented onDoubleClick and navigate to editor in FileContainer.tsx

[WEB-1_double_click_file] Implemented double click navigate to file.

---

frontend/src/packages/dashboard/components/SideBar/SideBar.tsx

Currently, the buttons on the sidebar have no icons. By adding universally recognised icons, users will be able to instantly know the functionality of each button.
In `frontend/src/packages/dashboard/components/Sidebar/Sidebar.tsx`:
- Edited styled component `SidebarButton` to have `display: flex`, in order to align the button icons and text properly.
- Created new styled components `ButtonIcon` and `ButtonText` to style the individual components of each button.
- Imported icons for each of the three buttons from the MUI Icon Library that most closely resembled those specified in the ticket. Integrated them into each button as required.

[WEB-3] add icons to new page, new folder, and edit button

---

frontend/src/packages/dashboard/components/ConfirmationModal/ConfirmationWindow.tsx

When creating a new file/folder the popup modal does not accept the enter key press to submit. Handling the enter key press provides better accessibility.
- added an onKeyDown event to the submission textfield in ConfirmationWindow.tsx
- created the event handler (handleKeyDown) that calls handleSubmit when pressed

[WEB-10] Handle enter key press when naming new file/folder

---

frontend/src/deprecated/components/Editor/EditorHeader.tsx
frontend/src/packages/editor/index.tsx

Currently in the editor, the sync and publish buttons are positioned next to the `insert heading/content block` buttons. As these buttons don't directly relate to the editing of the document, it is best to position them separately in the top right corner.
In  `frontend/src/packages/editor/index.tsx`:
- Changed the `EditorHeader` component to have both a opening and closing tag, in order to nest the sync and publish buttons within it.
- Nested `SyncDocument` and `PublishDocument` components within `EditorHeader`.
In `frontend/src/deprecated/components/Editor/EditorHeader.tsx`:
- Increased header size from `50px` to `65px`, in order to fully contain the sync and publish buttons without overflow.
- In `HeaderFlex` component, set `justify-content` to `flex-end` in order to align the buttons …

[WEB-4] [EDITOR] move sync and publish buttons to the top of the editor page

---

frontend/src/packages/dashboard/components/FileRenderer/Renamable.tsx

Why the changes are required
- the input box persists and the user may end up with multiple input boxes for changing the names of the files and folders
Changes
- the input box is automatically focused once the name is double clicked
- clicking outside the box will set the name

remove input box when user deselects the title of a folder or a file

---

frontend/src/packages/dashboard/Dashboard.tsx
frontend/src/packages/dashboard/components/Directory.tsx
frontend/src/packages/dashboard/state/folders/initial-state.ts
frontend/src/packages/dashboard/state/folders/reducers.ts
frontend/src/packages/dashboard/state/folders/types.ts

Breadcrumb pill path was not interactive and did not allow user to traverse the folder structure by clicking on it.
Repeatedly clicking on the root folder also caused the path to repeatedly print out 'root'.
- Implemented breadcrumb pill clicking functionality by altering how path was stored: string path -> array of objects storing folderId and folderNames
- Using the above change to an array, the repeating root in path was also fixed by checking if a certain folderId already existed in the path array.
Now that the path is stored in an array of objects, the traverseBackFolderSaga can simply be replaced by traverseIntoFolderSaga, so can potentially be removed.

[WEB-20] Clicking on folder pill in breadcrumb path redirects user to that folder

---

frontend/src/packages/dashboard/components/ConfirmationModal/ConfirmationWindow.tsx

Currently, when a user exits the new page / new folder modal, the input name persists in subsequent renders of the modal.
- `frontend/src/packages/dashboard/components/ConfirmationModal/ConfirmationWindow.tsx` - added a `useEffect` hook which resets the state of the input value whenever the modal is opened or closed.
https://github.com/csesoc/website/assets/79197816/54c27a8d-e437-4d4f-ac1d-a5b27a46a9c5

[WEB-32] [CMS] new file/folder name persistence issue fix

---

backend/database/repositories/main.go
backend/database/repositories/tests/filesystem_test.go
backend/editor/diffSync/document/manager.go
backend/endpoints/dependency_factory.go
backend/endpoints/main.go

Moving the construction of contexts outside of `Get___Repo()` functions into a parameter instead. This fixes a use case where uninitialised `Repo`s have a cyclical dependency on `TestingContext` (It's required to be defined, but cannot be at the same time).

Context Refactoring

---

frontend/src/packages/editor/components/CodeBlock.tsx
next/package-lock.json
next/package.json
next/src/components/blog/Blog-styled.tsx
next/src/components/blog/Blog.tsx
next/src/components/blog/types.ts
next/src/components/footer/Footer.tsx
next/src/pages/blog/[bid].tsx
next/yarn.lock

Currently, code blocks in published blogs are displayed as plain text without syntax highlighting.
- `next/src/components/blog/types.ts` - added type definitions for code blocks
- Imported `PrismJS` for syntax highlighting support
- `next/src/components/blog/Blog.tsx` - added handler for when `element.type == "code"` in order to properly display code blocks
- `next/src/components/blog/Blog-styled.tsx` - styling for code blocks
- Discovered a bug where republished documents would fail to load as a blog when a line is shorter than its original length. Further investigation required,

NEXT - Format Code Blocks on Blog Posts

---

frontend/src/cse-ui-kit/EditableTitle_textbox/EditableTitle-Styled.tsx
frontend/src/cse-ui-kit/EditableTitle_textbox/EditableTitle.tsx
frontend/src/cse-ui-kit/EditableTitle_textbox/index.ts
frontend/src/packages/editor/index.tsx

Currently there is no way to edit a document's filename while inside the editor.
I took inspiration from Google Docs and made it so that when a user hovers over the filename in the editor, the cursor turns into an I-beam and the title slightly enlarges. This indicates to the user that the title is editable. Then upon clicking, the title visibly becomes a text box which users can write into. Once they are done renaming, they click out of the text box and the new filename is saved :D 
- `frontend/src/cse-ui-kit/EditableTitle_textbox/*` - new component defining the custom text box for the editable file name
- `frontend/src/packages/editor/index.tsx` - integrated code to support file renaming. Reused code from `frontend/src/packages/dashboard/components/FileRenderer/Renamable.tsx` to update …

[WEB-65] [EDITOR] Make blog title editable within editor

---

frontend/src/packages/dashboard/components/ConfirmationModal/ConfirmationWindow.tsx

Currently, when the user opens the _New File_ or _New Modal_ modal, the text box to input the new file/folder name is unfocused by default. Also, when typing a new file name, the browser provides autocomplete suggestions based on previous inputs, which are mostly irrelevant in this context.
- Added `autoFocus` and `autoComplete = 'off'`  to the `TextField` in `ConfirmationModal.tsx` to enable auto focus and disable autocomplete.

[CMS] autofocus input box for new file/folder names

---

backend/endpoints/form_parsers.go

Originally there as an error parsing uploaded image requests. This is because `field.Type().Name()` returns a `string` of the field type and so an error was thrown from trying to read a non-existing file from the request.
Correcting this to `v.Type().Field(i).Name` changes it to a `string` of the field name.

Fix parsing form file reflection error
